### PR TITLE
Add more factories

### PR DESCRIPTION
**Pull request by ivantjh**
- Move utility methods for db into `/utils/dbUtil.ts`
- Come up with a suitable method for extending factories, will be useful if we really need to write tests

### CODE REVIEW

**Comment by zatkiller** [comment]
These are factory methods to write Jest Unit tests?

**Comment by ivantjh** [comment]
Yeap, these factory methods will allow you to easily create test models. E.g. `Stall` can consist of `Reviews`, `Categories` and `Images`. By using factory methods, we can create a Stall that contains `Reviews`, `Categories` and `Images` with minimal number of lines of code -> can then check the API response of retrieving that object to verify it is correct.

**Comment by ivantjh** [comment]
Need factory methods because to create a single review -> need to create a user too. These methods help to encapsulate that complexity, but of course have to first create these factory methods so they can be conveniently used in tests.

**Comment by zatkiller** [comment]
Alright looks good

**Review by zatkiller — APPROVED** [review]

**Pull request merged**
